import { writeFileSync, mkdirSync, existsSync, readFileSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const rootDir = join(__dirname, '..');

// Read the wrangler.json generated by TanStack Start build
// For cloudflare-workers preset, it outputs to .output/wrangler.json
let generated = { d1_databases: [] };
const wranglerJsonPath = join(rootDir, '.output/wrangler.json');

if (existsSync(wranglerJsonPath)) {
  generated = JSON.parse(readFileSync(wranglerJsonPath, 'utf-8'));
}

// Create our deploy config for Cloudflare Workers
// Uses .output/ directory (TanStack Start cloudflare-workers preset output)
const deployConfig = {
  name: 'smtp-forge',
  main: '.output/server/index.js',
  compatibility_date: '2024-04-01',
  compatibility_flags: ['nodejs_compat_v2'],
  // Include D1 databases from generated config or root wrangler.jsonc
  d1_databases: generated.d1_databases?.length 
    ? generated.d1_databases 
    : [],
  vars: {
    APP_ENV: 'production'
  },
  assets: '.output/public',
  // Edge compute optimization (requires Workers Paid plan)
  // Remove this section if on free tier
  placement: {
    mode: 'smart'
  },
  build: {
    upload_environment_variables: ['APP_ENV']
  }
};

const outputPath = join(rootDir, '.output/wrangler.deploy.json');
const outputDir = dirname(outputPath);

if (!existsSync(outputDir)) {
  mkdirSync(outputDir, { recursive: true });
}

writeFileSync(outputPath, JSON.stringify(deployConfig, null, 2));
console.log('✓ Created .output/wrangler.deploy.json');
console.log('  Main entry:', deployConfig.main);
console.log('  Assets:', deployConfig.assets);
console.log('  D1 databases:', deployConfig.d1_databases.length);
console.log('');
console.log('Deploy with: wrangler deploy .output/wrangler.deploy.json');