/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppServersRouteImport } from './routes/_app.servers'
import { Route as AppDomainsRouteImport } from './routes/_app.domains'
import { Route as AppDomainsIdRouteImport } from './routes/_app.domains.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppServersRoute = AppServersRouteImport.update({
  id: '/servers',
  path: '/servers',
  getParentRoute: () => AppRoute,
} as any)
const AppDomainsRoute = AppDomainsRouteImport.update({
  id: '/domains',
  path: '/domains',
  getParentRoute: () => AppRoute,
} as any)
const AppDomainsIdRoute = AppDomainsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppDomainsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/auth': typeof AuthRoute
  '/domains': typeof AppDomainsRouteWithChildren
  '/servers': typeof AppServersRoute
  '/settings': typeof AppSettingsRoute
  '/domains/$id': typeof AppDomainsIdRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/domains': typeof AppDomainsRouteWithChildren
  '/servers': typeof AppServersRoute
  '/settings': typeof AppSettingsRoute
  '/': typeof AppIndexRoute
  '/domains/$id': typeof AppDomainsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRoute
  '/_app/domains': typeof AppDomainsRouteWithChildren
  '/_app/servers': typeof AppServersRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/': typeof AppIndexRoute
  '/_app/domains/$id': typeof AppDomainsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/domains'
    | '/servers'
    | '/settings'
    | '/domains/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/auth' | '/domains' | '/servers' | '/settings' | '/' | '/domains/$id'
  id:
    | '__root__'
    | '/_app'
    | '/auth'
    | '/_app/domains'
    | '/_app/servers'
    | '/_app/settings'
    | '/_app/'
    | '/_app/domains/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/servers': {
      id: '/_app/servers'
      path: '/servers'
      fullPath: '/servers'
      preLoaderRoute: typeof AppServersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/domains': {
      id: '/_app/domains'
      path: '/domains'
      fullPath: '/domains'
      preLoaderRoute: typeof AppDomainsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/domains/$id': {
      id: '/_app/domains/$id'
      path: '/$id'
      fullPath: '/domains/$id'
      preLoaderRoute: typeof AppDomainsIdRouteImport
      parentRoute: typeof AppDomainsRoute
    }
  }
}

interface AppDomainsRouteChildren {
  AppDomainsIdRoute: typeof AppDomainsIdRoute
}

const AppDomainsRouteChildren: AppDomainsRouteChildren = {
  AppDomainsIdRoute: AppDomainsIdRoute,
}

const AppDomainsRouteWithChildren = AppDomainsRoute._addFileChildren(
  AppDomainsRouteChildren,
)

interface AppRouteChildren {
  AppDomainsRoute: typeof AppDomainsRouteWithChildren
  AppServersRoute: typeof AppServersRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDomainsRoute: AppDomainsRouteWithChildren,
  AppServersRoute: AppServersRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
